# Generated by scripts/release.py; edit packaging/templates/install.ps1.
param(
    [Parameter(Mandatory=$true)][string]$Version,
    [string]$InstallDir = (Join-Path $env:LOCALAPPDATA 'sjskills\bin'),
    [string]$ArchiveDir = ''
)
$ErrorActionPreference = 'Stop'
if ($Version -cnotmatch '^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$') { throw 'Invalid stable version' }
if ([Environment]::OSVersion.Platform -ne 'Win32NT') { throw 'Unsupported platform' }
$architecture = [System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString()
switch ($architecture) {
@WINDOWS_TARGETS@
    default { throw "Unsupported architecture: $architecture" }
}
$null = New-Item -ItemType Directory -Force -Path $InstallDir
$InstallDir = (Resolve-Path -LiteralPath $InstallDir).Path
$destination = Join-Path $InstallDir 'sjskills.exe'
if (Test-Path -LiteralPath $destination) {
    $existing = Get-Item -LiteralPath $destination -Force
    if ($existing.PSIsContainer -or ($existing.Attributes -band [IO.FileAttributes]::ReparsePoint)) { throw 'Destination is a directory or link' }
}
$work = Join-Path $InstallDir ('.sjskills-install.' + [guid]::NewGuid().ToString('N'))
$null = New-Item -ItemType Directory -Path $work
try {
    $base = "https://github.com/sjunepark/agent-scripts/releases/download/sjskills-v$Version"
    foreach ($name in @('SHA256SUMS', $asset)) {
        $output = Join-Path $work $name
        if ($ArchiveDir) { Copy-Item -LiteralPath (Join-Path $ArchiveDir $name) -Destination $output }
        else { Invoke-WebRequest -Uri "$base/$name" -OutFile $output }
    }
    $lines = @(Get-Content -LiteralPath (Join-Path $work 'SHA256SUMS') | Where-Object { $_ -cmatch ('^[a-f0-9]{64}  ' + [regex]::Escape($asset) + '$') })
    if ($lines.Count -ne 1) { throw 'Missing or ambiguous checksum' }
    $expected = $lines[0].Substring(0,64)
    if ((Get-FileHash -Algorithm SHA256 -LiteralPath (Join-Path $work $asset)).Hash.ToLowerInvariant() -cne $expected) { throw 'Checksum mismatch' }
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    $zip = [IO.Compression.ZipFile]::OpenRead((Join-Path $work $asset))
    try {
        $names = @($zip.Entries | ForEach-Object { $_.FullName } | Sort-Object)
        if (($names -join ',') -cne 'release.json,sjskills.exe') { throw 'Unexpected archive contents' }
        $candidate = Join-Path $work 'sjskills.exe'
        [IO.Compression.ZipFileExtensions]::ExtractToFile($zip.GetEntry('sjskills.exe'), $candidate)
    } finally { $zip.Dispose() }
    $identity = & $candidate --version
    if ($LASTEXITCODE -ne 0 -or $identity -cne "sjskills $Version") { throw 'Binary version mismatch' }
    if (Test-Path -LiteralPath $destination) { [IO.File]::Replace($candidate, $destination, $null) }
    else { [IO.File]::Move($candidate, $destination) }
    Write-Host "Installed sjskills $Version to $destination. Add $InstallDir to PATH."
} finally { Remove-Item -LiteralPath $work -Recurse -Force }
