#!/bin/sh
# Generated by scripts/release.py; edit packaging/templates/install.sh.
set -eu
fail() { echo "sjskills install: $*" >&2; exit 1; }
version=${1:-}
[ "$#" -ge 1 ] && [ "$#" -le 3 ] || fail 'usage: install.sh VERSION [INSTALL_DIR [ARCHIVE_DIR]]'
# Stable numeric versions only; no path or URL fragments enter downloads.
case "$version" in *[!0-9.]*|'') fail 'expected version such as 1.0.0' ;; esac
printf '%s\n' "$version" | awk -F. 'NF != 3 {exit 1} {for(i=1;i<=3;i++) if($i == "" || ($i ~ /^0/ && length($i)>1)) exit 1}' || fail 'invalid version'
case "$(uname -s):$(uname -m)" in
@UNIX_TARGETS@
  *) fail 'unsupported platform' ;;
esac
install_dir=${2:-"$HOME/.local/bin"}
archive_dir=${3:-}
mkdir -p "$install_dir"
install_dir=$(CDPATH= cd -- "$install_dir" && pwd)
[ ! -d "$install_dir/sjskills" ] || fail 'destination is a directory'
[ ! -L "$install_dir/sjskills" ] || fail 'destination is a symlink; select a different installation directory'
work=$(mktemp -d "$install_dir/.sjskills-install.XXXXXX")
trap 'rm -rf "$work"' EXIT HUP INT TERM
base="https://github.com/sjunepark/agent-scripts/releases/download/sjskills-v$version"
fetch() {
  if [ -n "$archive_dir" ]; then
    cp "$archive_dir/$1" "$work/$1"
  else
    curl --fail --silent --show-error --location --proto '=https' --proto-redir '=https' "$base/$1" -o "$work/$1"
  fi
}
fetch SHA256SUMS
fetch "$asset"
expected=$(awk -v asset="$asset" '$2 == asset {print $1}' "$work/SHA256SUMS")
[ "${#expected}" -eq 64 ] || fail 'missing or ambiguous checksum'
case "$expected" in *[!0-9a-f]*) fail 'invalid checksum' ;; esac
actual=$(shasum -a 256 "$work/$asset" | awk '{print $1}')
[ "$actual" = "$expected" ] || fail 'checksum mismatch'
# Extract only the expected regular executable, never arbitrary archive paths.
[ "$(tar -tzf "$work/$asset" | sort)" = "$(printf 'release.json\nsjskills\n')" ] || fail 'unexpected archive contents'
[ "$(tar -tvzf "$work/$asset" | cut -c1 | sort -u)" = '-' ] || fail 'archive contains non-regular files'
tar -xzf "$work/$asset" -C "$work" sjskills
chmod 755 "$work/sjskills"
[ "$("$work/sjskills" --version)" = "sjskills $version" ] || fail 'binary version mismatch'
mv -f "$work/sjskills" "$install_dir/sjskills"
printf 'Installed sjskills %s to %s/sjskills. Add %s to PATH.\n' "$version" "$install_dir" "$install_dir" >&2
